/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f2fd",
        "surface-container": "#eeedf7",
        "surface-container-high": "#e8e7f1",
        "surface-container-highest": "#e3e1ec",
        "surface": "#fbf8ff",
        "surface-dim": "#dad9e3",
        "surface-bright": "#fbf8ff",
        "surface-variant": "#e3e1ec",
        "on-surface": "#1a1b22",
        "on-surface-variant": "#434655",
        "inverse-surface": "#2f3038",
        "inverse-on-surface": "#f1effa",
        "primary": "#004ac6",
        "primary-container": "#2563eb",
        "on-primary": "#ffffff",
        "on-primary-container": "#eeefff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "secondary": "#5f5e60",
        "secondary-container": "#e5e1e4",
        "secondary-fixed": "#e5e1e4",
        "secondary-fixed-dim": "#c8c6c8",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#656466",
        "tertiary": "#006242",
        "tertiary-container": "#007d55",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#bdffdb",
        "on-tertiary-fixed": "#002113",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#737686",
        "outline-variant": "#c3c6d7",
        "background": "#fbf8ff",
        "on-background": "#1a1b22",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "margin-desktop": "2rem",
      },
      boxShadow: {
        "subtle": "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.03)",
        "card": "0 1px 8px rgba(0, 0, 0, 0.04)",
      }
    },
  },
  plugins: [],
}
