/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed": "#002113",
        "error-container": "#93000a",
        "on-tertiary-container": "#3e2400",
        "secondary-fixed-dim": "#4edea3",
        "secondary-fixed": "#6ffbbe",
        "on-primary-container": "#0d0096",
        "primary": "#c0c1ff",
        "tertiary-container": "#ca8100",
        "primary-container": "#8083ff",
        "surface-container": "#1c1f29",
        "on-tertiary": "#472a00",
        "on-secondary": "#003824",
        "secondary-container": "#00a572",
        "tertiary-fixed-dim": "#ffb95f",
        "on-background": "#dfe2ef",
        "secondary": "#4edea3",
        "on-surface": "#dfe2ef",
        "surface-variant": "#31353f",
        "inverse-surface": "#dfe2ef",
        "outline-variant": "#464554",
        "surface-container-high": "#262a34",
        "on-error": "#690005",
        "background": "#0f131c",
        "tertiary-fixed": "#ffddb8",
        "outline": "#908fa0",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-highest": "#31353f",
        "surface": "#0f131c",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-on-surface": "#2c303a",
        "surface-tint": "#c0c1ff",
        "on-secondary-container": "#00311f",
        "surface-bright": "#353943",
        "tertiary": "#ffb95f",
        "surface-dim": "#0f131c",
        "surface-container-lowest": "#0a0e17",
        "on-tertiary-fixed": "#2a1700",
        "error": "#ffb4ab",
        "on-primary-fixed": "#07006c",
        "on-surface-variant": "#c7c4d7",
        "primary-fixed": "#e1e0ff",
        "on-primary": "#1000a9",
        "inverse-primary": "#494bd6",
        "surface-container-low": "#181b25",
        "on-error-container": "#ffdad6"
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "Space Mono", "monospace"],
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shake': 'denialShake 0.6s cubic-bezier(0.36, 0.07, 0.19, 0.97) both',
        'bloom': 'emeraldBloom 0.8s ease-out forwards',
        'scan': 'cyberScan 2s linear infinite',
      },
      keyframes: {
        denialShake: {
          '10%, 90%': { transform: 'translate3d(-2px, 0, 0) scale(0.98)' },
          '20%, 80%': { transform: 'translate3d(4px, 0, 0) scale(0.98)' },
          '30%, 50%, 70%': { transform: 'translate3d(-6px, 0, 0) scale(0.98)' },
          '40%, 60%': { transform: 'translate3d(6px, 0, 0) scale(0.98)' },
        },
        emeraldBloom: {
          '0%': { transform: 'scale(0.95)', boxShadow: '0 0 0 rgba(78, 222, 163, 0)' },
          '50%': { transform: 'scale(1.04)', boxShadow: '0 0 35px rgba(78, 222, 163, 0.8)' },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 20px rgba(78, 222, 163, 0.4)' },
        },
        cyberScan: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        }
      }
    },
  },
  plugins: [],
}
