import type { SpeciesInfo } from '../types/pet';

export const SPECIES_CATALOG: Record<string, SpeciesInfo> = {
  egg: {
    id: 'egg',
    name: 'Cosmic Embryo',
    stage: 'EGG',
    description: 'An iridescent, warm-shelled digital egg humming with dormant celestial DNA.',
    primaryColor: '#f1f5f9',
    secondaryColor: '#cbd5e1',
    accentColor: '#38bdf8',
    features: ['Glowing rune cracks', 'Warm core pulse', 'Interactive tapping hatch'],
    dietPreference: 'Incubator Warmth',
    epigeneticRequirement: 'Ready to hatch upon player bond tap',
    avatarEmoji: '🥚',
  },
  blobkin: {
    id: 'blobkin',
    name: 'Blobkin',
    stage: 'BABY',
    description: 'A bouncy, translucent gelatinous companion with wide, curious eyes and an insatiable appetite.',
    primaryColor: '#38bdf8',
    secondaryColor: '#0284c7',
    accentColor: '#fb7185',
    features: ['Gelatinous jiggle', 'Curious eye blinks', 'Cheek blush'],
    dietPreference: 'Soft Berries & Pure Water',
    epigeneticRequirement: 'Base stage for all epigenetic branching',
    avatarEmoji: '🫧',
  },
  chibi_sprout: {
    id: 'chibi_sprout',
    name: 'Chibi Sprout',
    stage: 'CHILD',
    description: 'A cheerful toddler pet sporting a sensitive photosynthetic leaf antenna that wilts in dirty air.',
    primaryColor: '#4ade80',
    secondaryColor: '#16a34a',
    accentColor: '#fde047',
    features: ['Photosynthetic leaf', 'Chlorophyll glow', 'Dewdrop tail'],
    dietPreference: 'Fibrous Solar Berries',
    epigeneticRequirement: 'Hygiene Average > 0.70',
    avatarEmoji: '🌱',
  },
  nibble_pug: {
    id: 'nibble_pug',
    name: 'Nibble Pug',
    stage: 'CHILD',
    description: 'A fierce yet huggable dragon puppy with a bottomless stomach for protein treats and ball fetch.',
    primaryColor: '#fb923c',
    secondaryColor: '#ea580c',
    accentColor: '#facc15',
    features: ['Tiny dragon fangs', 'Playful wag tail', 'Springy pounce'],
    dietPreference: 'Savory Prime Protein',
    epigeneticRequirement: 'Protein Intake > Sugar Intake',
    avatarEmoji: '🐕',
  },
  sparkle_mite: {
    id: 'sparkle_mite',
    name: 'Sparkle Mite',
    stage: 'CHILD',
    description: 'A hyperactive hovering orb of sugar-fueled plasma that leaves sparkling comet dust in its wake.',
    primaryColor: '#c084fc',
    secondaryColor: '#9333ea',
    accentColor: '#f472b6',
    features: ['Plasma trail', 'Floating levitation', 'Sweet-tooth aura'],
    dietPreference: 'Sugary Nectar Glaze',
    epigeneticRequirement: 'Sugar Intake > Protein Intake',
    avatarEmoji: '✨',
  },
  verdant_cub: {
    id: 'verdant_cub',
    name: 'Verdant Cub',
    stage: 'TEEN',
    description: 'An agile forest feline with moss-dappled fur and a natural affinity for clean, open terrariums.',
    primaryColor: '#10b981',
    secondaryColor: '#047857',
    accentColor: '#a7f3d0',
    features: ['Foliage crest', 'Silent pounce paws', 'Breeze whiskers'],
    dietPreference: 'Balanced Organic Berries',
    epigeneticRequirement: 'High Hygiene & Balanced Nutrition',
    avatarEmoji: '🌿',
  },
  pyro_fang: {
    id: 'pyro_fang',
    name: 'Pyro Fang',
    stage: 'TEEN',
    description: 'A muscular adolescent drake whose scales glow like cooling lava. Craves constant exercise and heavy proteins.',
    primaryColor: '#f43f5e',
    secondaryColor: '#be123c',
    accentColor: '#fbbf24',
    features: ['Ember dorsal crest', 'Smoldering breath', 'Tough horns'],
    dietPreference: 'Hearty Roasted Meat',
    epigeneticRequirement: 'High Protein + Play Discipline > 0.55',
    avatarEmoji: '🔥',
  },
  glimmer_sprite: {
    id: 'glimmer_sprite',
    name: 'Glimmer Sprite',
    stage: 'TEEN',
    description: 'An ethereal fluttering companion adorned with confectionery wing patterns that shimmer in moonlight.',
    primaryColor: '#e879f9',
    secondaryColor: '#c026d3',
    accentColor: '#38bdf8',
    features: ['Prismatic wings', 'Dream dust flutter', 'Star halo'],
    dietPreference: 'Cotton Star Drops',
    epigeneticRequirement: 'Sugar Intake >= 60 & High Happiness',
    avatarEmoji: '🧚',
  },
  iron_shell: {
    id: 'iron_shell',
    name: 'Iron Shell',
    stage: 'TEEN',
    description: 'A stoic, armored guardian whose shell absorbs shocks. Calm, methodical, and disciplined in sleep.',
    primaryColor: '#64748b',
    secondaryColor: '#334155',
    accentColor: '#38bdf8',
    features: ['Titanium carapace', 'Stoic visor eyes', 'Heavy stomp'],
    dietPreference: 'Mineral Fortified Protein',
    epigeneticRequirement: 'Consistent Sleep & Discipline > 0.65',
    avatarEmoji: '🛡️',
  },
  cyber_drake: {
    id: 'cyber_drake',
    name: 'Cyber Drake',
    stage: 'ADULT',
    description: 'A legendary dragon fused with sleek luminescent cyberware. Channeling data pulses and lightning reflexes.',
    primaryColor: '#06b6d4',
    secondaryColor: '#0e7490',
    accentColor: '#f43f5e',
    features: ['Holographic dorsal fins', 'Neon optic circuits', 'Plasma tail jet'],
    dietPreference: 'Synthesized Super-Fuel',
    epigeneticRequirement: 'High Discipline + High Protein + High Experience',
    avatarEmoji: '🐉',
  },
  mossy_boulderkind: {
    id: 'mossy_boulderkind',
    name: 'Mossy Boulderkind',
    stage: 'ADULT',
    description: 'A gentle earthen colossus crowned with living bonsai trees and glowing crystalline runes.',
    primaryColor: '#84cc16',
    secondaryColor: '#4d7c0f',
    accentColor: '#d97706',
    features: ['Living canopy', 'Rune-carved stone body', 'Terrarium harmony'],
    dietPreference: 'Deep Earth Truffles & Pure Spring Dew',
    epigeneticRequirement: 'Pristine Hygiene Avg >= 0.85 & Patient Care',
    avatarEmoji: '🗿',
  },
  astral_wisp: {
    id: 'astral_wisp',
    name: 'Astral Wisp',
    stage: 'ADULT',
    description: 'A transcendent cosmic entity woven from nebulous starlight. Drifts weightlessly through the terrarium.',
    primaryColor: '#818cf8',
    secondaryColor: '#4338ca',
    accentColor: '#f472b6',
    features: ['Starlight corona', 'Zero-gravity drift', 'Constellation aura'],
    dietPreference: 'Starlight Nectar & Dream Sugar',
    epigeneticRequirement: 'High Sugar + Ecstatic Mood Retention',
    avatarEmoji: '🌌',
  },
  solar_gryphon: {
    id: 'solar_gryphon',
    name: 'Solar Gryphon',
    stage: 'ADULT',
    description: 'A majestic winged beast of gilded feathers that gathers solar radiance to protect its sanctuary.',
    primaryColor: '#f59e0b',
    secondaryColor: '#b45309',
    accentColor: '#38bdf8',
    features: ['Gilded plumage', 'Sunbeam crown', 'Aerodynamic wing span'],
    dietPreference: 'Golden Solar Fruit',
    epigeneticRequirement: 'Hygiene >= 0.80 & Discipline >= 0.70',
    avatarEmoji: '🦅',
  },
  voidling: {
    id: 'voidling',
    name: 'Shadow Voidling',
    stage: 'ADULT',
    description: 'An enigmatic being forged from velvet twilight. Intensely bonded to quiet nights and secret snacks.',
    primaryColor: '#475569',
    secondaryColor: '#1e293b',
    accentColor: '#a855f7',
    features: ['Shadow tentacles', 'Amethyst glowing gaze', 'Nocturnal phasing'],
    dietPreference: 'Moon Truffles & Sweet Glaze',
    epigeneticRequirement: 'Night-Active Lifestyle & Sweet Affinity',
    avatarEmoji: '🌑',
  },
  mecha_titan: {
    id: 'mecha_titan',
    name: 'Mecha Titan',
    stage: 'ADULT',
    description: 'An unstoppable steam-powered armored dreadnought with hydraulic limbs and iron-clad willpower.',
    primaryColor: '#f97316',
    secondaryColor: '#c2410c',
    accentColor: '#38bdf8',
    features: ['Hydraulic steam vents', 'Heavy rivet armor', 'Core reactor glow'],
    dietPreference: 'Heavy Calorie Steaks',
    epigeneticRequirement: 'Protein Intake >= 100 & Exercise Master',
    avatarEmoji: '⚙️',
  },
  celestial_guardian: {
    id: 'celestial_guardian',
    name: 'Celestial Guardian',
    stage: 'ANCIENT',
    description: 'The pinnacle of holistic nurture. A mythical deity that commands celestial harmony and infinite rebirth.',
    primaryColor: '#ec4899',
    secondaryColor: '#8b5cf6',
    accentColor: '#38bdf8',
    features: ['Multi-dimensional wings', 'Prismatic halo', 'Immortality glyphs'],
    dietPreference: 'Ambrosia of the Cosmos',
    epigeneticRequirement: 'Holistic Mastery across all vitals and care history',
    avatarEmoji: '👑',
  },
};

export const INITIAL_FOODS = [
  {
    id: 'sun_berry',
    name: 'Sun Berry',
    category: 'FRUIT' as const,
    hungerRestore: 18,
    happinessRestore: 12,
    epigeneticModifiers: { hygieneCareAverage: 0.05, sugarIntake: 5 },
    quantity: 6,
    icon: '🍓',
    description: 'Sweet and rich in natural antioxidants.',
    color: '#fb7185',
  },
  {
    id: 'crisp_apple',
    name: 'Celeste Apple',
    category: 'FRUIT' as const,
    hungerRestore: 22,
    happinessRestore: 15,
    epigeneticModifiers: { sugarIntake: 8 },
    quantity: 4,
    icon: '🍎',
    description: 'Crunchy orchard favorite that boosts natural energy.',
    color: '#f43f5e',
  },
  {
    id: 'prime_steak',
    name: 'Prime Steak',
    category: 'MEAT' as const,
    hungerRestore: 40,
    happinessRestore: 20,
    epigeneticModifiers: { proteinIntake: 25, playDisciplineRatio: 0.05 },
    quantity: 3,
    icon: '🥩',
    description: 'High-density protein for muscular growth and physical evolution.',
    color: '#e11d48',
  },
  {
    id: 'grilled_fish',
    name: 'River Trout',
    category: 'MEAT' as const,
    hungerRestore: 32,
    happinessRestore: 18,
    epigeneticModifiers: { proteinIntake: 18 },
    quantity: 4,
    icon: '🐟',
    description: 'Lean and savory fish that sharpens mental reflexes.',
    color: '#0284c7',
  },
  {
    id: 'star_candy',
    name: 'Star Candy',
    category: 'SWEET' as const,
    hungerRestore: 10,
    happinessRestore: 35,
    epigeneticModifiers: { sugarIntake: 22 },
    quantity: 5,
    icon: '🍬',
    description: 'Pure joy in confection form! High happiness but zero fiber.',
    color: '#ec4899',
  },
  {
    id: 'honey_donut',
    name: 'Honey Donut',
    category: 'SWEET' as const,
    hungerRestore: 25,
    happinessRestore: 30,
    epigeneticModifiers: { sugarIntake: 28 },
    quantity: 3,
    icon: '🍩',
    description: 'Glazed with golden nectar; unlocks the sugar-wisp pathway.',
    color: '#f59e0b',
  },
  {
    id: 'herbal_elixir',
    name: 'Herbal Elixir',
    category: 'MEDICINE' as const,
    hungerRestore: 5,
    happinessRestore: 15,
    epigeneticModifiers: { hygieneCareAverage: 0.1 },
    quantity: 2,
    icon: '🧪',
    description: 'Cures sickness, eliminates biological toxins, and restores vitality.',
    color: '#10b981',
  },
];
