import { getFoodImageUrl } from './generateImageUrl';

export interface Recipe {
  id: string;
  name: string;
  category: 'breakfast' | 'lunch' | 'dinner' | 'dessert' | 'pre-workout' | 'post-workout';
  protein: number;
  carbs: number;
  fats: number;
  calories: number;
  ingredients: string[];
  instructions: string[];
  image?: string;
  prepTime: number;
  cookTime: number;
}

const recipesData: Recipe[] = [
  // Breakfast Recipes (20)
  {
    id: 'bf-1',
    name: 'Protein-Packed Scrambled Eggs',
    category: 'breakfast',
    protein: 35,
    carbs: 5,
    fats: 20,
    calories: 340,
    ingredients: ['6 large eggs', '1 cup cottage cheese', '2 tbsp olive oil', 'Spinach', 'Salt & pepper'],
    instructions: ['Whisk eggs with cottage cheese', 'Heat oil in pan', 'Add eggs and scramble', 'Add spinach at the end'],
    prepTime: 5,
    cookTime: 10,
    image: 'https://source.unsplash.com/400x300/?scrambled-eggs-breakfast&sig=1',
  },
  {
    id: 'bf-2',
    name: 'Greek Yogurt Protein Bowl',
    category: 'breakfast',
    protein: 40,
    carbs: 25,
    fats: 8,
    calories: 320,
    ingredients: ['2 cups Greek yogurt', '1 scoop protein powder', 'Berries', 'Almonds', 'Honey'],
    instructions: ['Mix yogurt with protein powder', 'Top with berries and almonds', 'Drizzle with honey'],
    prepTime: 5,
    cookTime: 0,
    image: 'https://source.unsplash.com/400x300/?greek-yogurt-bowl&sig=2',
  },
  {
    id: 'bf-3',
    name: 'Chicken Sausage Omelet',
    category: 'breakfast',
    protein: 42,
    carbs: 8,
    fats: 22,
    calories: 380,
    ingredients: ['4 eggs', '2 chicken sausages', 'Bell peppers', 'Onions', 'Cheese'],
    instructions: ['Cook sausages and vegetables', 'Beat eggs', 'Make omelet with fillings'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'bf-4',
    name: 'Protein Pancakes',
    category: 'breakfast',
    protein: 38,
    carbs: 30,
    fats: 12,
    calories: 360,
    ingredients: ['2 scoops protein powder', '2 eggs', '1 banana', 'Oat flour', 'Baking powder'],
    instructions: ['Mix all ingredients', 'Cook on griddle', 'Serve with berries'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'bf-5',
    name: 'Smoked Salmon & Eggs',
    category: 'breakfast',
    protein: 36,
    carbs: 3,
    fats: 18,
    calories: 310,
    ingredients: ['4 oz smoked salmon', '3 eggs', 'Cream cheese', 'Capers', 'Red onion'],
    instructions: ['Poach eggs', 'Serve with salmon', 'Garnish with capers and onion'],
    prepTime: 5,
    cookTime: 10,
  },
  {
    id: 'bf-6',
    name: 'Turkey Bacon & Egg Muffins',
    category: 'breakfast',
    protein: 28,
    carbs: 6,
    fats: 15,
    calories: 260,
    ingredients: ['6 eggs', '6 slices turkey bacon', 'Spinach', 'Cheese', 'Muffin tin'],
    instructions: ['Line muffin tin with bacon', 'Add eggs and vegetables', 'Bake at 350°F for 20 min'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'bf-7',
    name: 'Protein Smoothie Bowl',
    category: 'breakfast',
    protein: 35,
    carbs: 35,
    fats: 10,
    calories: 340,
    ingredients: ['Protein powder', 'Frozen berries', 'Banana', 'Greek yogurt', 'Granola'],
    instructions: ['Blend fruits with protein', 'Pour into bowl', 'Top with granola'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'bf-8',
    name: 'Chicken & Quinoa Breakfast Bowl',
    category: 'breakfast',
    protein: 45,
    carbs: 40,
    fats: 12,
    calories: 420,
    ingredients: ['6 oz chicken breast', '1 cup cooked quinoa', 'Eggs', 'Avocado', 'Salsa'],
    instructions: ['Cook chicken and quinoa', 'Fry eggs', 'Assemble bowl with all ingredients'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'bf-9',
    name: 'High-Protein Overnight Oats',
    category: 'breakfast',
    protein: 32,
    carbs: 45,
    fats: 14,
    calories: 440,
    ingredients: ['1 cup oats', '1 scoop protein powder', 'Greek yogurt', 'Almond milk', 'Chia seeds'],
    instructions: ['Mix all ingredients', 'Refrigerate overnight', 'Top with nuts in morning'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'bf-10',
    name: 'Steak & Eggs',
    category: 'breakfast',
    protein: 48,
    carbs: 4,
    fats: 25,
    calories: 420,
    ingredients: ['6 oz sirloin steak', '3 eggs', 'Butter', 'Garlic', 'Herbs'],
    instructions: ['Cook steak to medium', 'Fry eggs in butter', 'Season with herbs'],
    prepTime: 5,
    cookTime: 15,
  },
  {
    id: 'bf-11',
    name: 'Protein Waffles',
    category: 'breakfast',
    protein: 36,
    carbs: 32,
    fats: 11,
    calories: 360,
    ingredients: ['Protein powder', 'Eggs', 'Almond flour', 'Baking powder', 'Vanilla'],
    instructions: ['Mix batter', 'Cook in waffle iron', 'Serve with protein syrup'],
    prepTime: 10,
    cookTime: 10,
  },
  {
    id: 'bf-12',
    name: 'Tuna & Avocado Toast',
    category: 'breakfast',
    protein: 34,
    carbs: 28,
    fats: 16,
    calories: 380,
    ingredients: ['Whole grain bread', 'Canned tuna', 'Avocado', 'Lemon', 'Red pepper flakes'],
    instructions: ['Toast bread', 'Mash avocado', 'Mix tuna with lemon', 'Assemble'],
    prepTime: 5,
    cookTime: 5,
  },
  {
    id: 'bf-13',
    name: 'Protein French Toast',
    category: 'breakfast',
    protein: 30,
    carbs: 35,
    fats: 10,
    calories: 340,
    ingredients: ['Whole grain bread', 'Eggs', 'Protein powder', 'Cinnamon', 'Vanilla'],
    instructions: ['Dip bread in egg mixture', 'Cook on griddle', 'Top with berries'],
    prepTime: 10,
    cookTime: 10,
  },
  {
    id: 'bf-14',
    name: 'Chicken Breakfast Burrito',
    category: 'breakfast',
    protein: 42,
    carbs: 38,
    fats: 14,
    calories: 440,
    ingredients: ['Tortilla', 'Chicken breast', 'Eggs', 'Black beans', 'Cheese', 'Salsa'],
    instructions: ['Cook chicken and eggs', 'Warm tortilla', 'Assemble burrito'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'bf-15',
    name: 'Protein Chia Pudding',
    category: 'breakfast',
    protein: 28,
    carbs: 25,
    fats: 18,
    calories: 360,
    ingredients: ['Chia seeds', 'Protein powder', 'Almond milk', 'Vanilla', 'Berries'],
    instructions: ['Mix chia with milk and protein', 'Refrigerate 4 hours', 'Top with berries'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'bf-16',
    name: 'Egg White Frittata',
    category: 'breakfast',
    protein: 32,
    carbs: 8,
    fats: 12,
    calories: 260,
    ingredients: ['12 egg whites', 'Turkey', 'Vegetables', 'Cheese', 'Herbs'],
    instructions: ['Mix all ingredients', 'Bake at 375°F for 25 min', 'Slice and serve'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'bf-17',
    name: 'Protein Oatmeal with Nuts',
    category: 'breakfast',
    protein: 30,
    carbs: 42,
    fats: 16,
    calories: 420,
    ingredients: ['Oats', 'Protein powder', 'Almonds', 'Walnuts', 'Honey'],
    instructions: ['Cook oats', 'Stir in protein powder', 'Top with nuts and honey'],
    prepTime: 5,
    cookTime: 10,
  },
  {
    id: 'bf-18',
    name: 'Breakfast Sausage & Hash',
    category: 'breakfast',
    protein: 38,
    carbs: 35,
    fats: 18,
    calories: 440,
    ingredients: ['Turkey sausage', 'Sweet potatoes', 'Onions', 'Peppers', 'Eggs'],
    instructions: ['Cook sausage and hash', 'Fry eggs', 'Serve together'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'bf-19',
    name: 'Protein Breakfast Cookies',
    category: 'breakfast',
    protein: 26,
    carbs: 28,
    fats: 12,
    calories: 320,
    ingredients: ['Protein powder', 'Oats', 'Banana', 'Almond butter', 'Chocolate chips'],
    instructions: ['Mix all ingredients', 'Form cookies', 'Bake at 350°F for 12 min'],
    prepTime: 10,
    cookTime: 12,
  },
  {
    id: 'bf-20',
    name: 'High-Protein Breakfast Casserole',
    category: 'breakfast',
    protein: 40,
    carbs: 12,
    fats: 20,
    calories: 380,
    ingredients: ['Eggs', 'Chicken', 'Vegetables', 'Cheese', 'Herbs'],
    instructions: ['Layer ingredients in dish', 'Bake at 375°F for 35 min', 'Let cool and slice'],
    prepTime: 15,
    cookTime: 35,
  },
  
  // Lunch Recipes (20)
  {
    id: 'ln-1',
    name: 'Grilled Chicken Salad',
    category: 'lunch',
    protein: 45,
    carbs: 15,
    fats: 18,
    calories: 380,
    ingredients: ['8 oz chicken breast', 'Mixed greens', 'Cherry tomatoes', 'Cucumber', 'Olive oil dressing'],
    instructions: ['Grill chicken', 'Chop vegetables', 'Toss salad', 'Add dressing'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'ln-2',
    name: 'Turkey & Quinoa Bowl',
    category: 'lunch',
    protein: 42,
    carbs: 45,
    fats: 14,
    calories: 460,
    ingredients: ['6 oz ground turkey', 'Quinoa', 'Black beans', 'Corn', 'Avocado', 'Salsa'],
    instructions: ['Cook turkey and quinoa', 'Assemble bowl', 'Top with avocado and salsa'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'ln-3',
    name: 'Tuna Salad Lettuce Wraps',
    category: 'lunch',
    protein: 38,
    carbs: 8,
    fats: 16,
    calories: 320,
    ingredients: ['Canned tuna', 'Greek yogurt', 'Celery', 'Lettuce leaves', 'Lemon'],
    instructions: ['Mix tuna with yogurt', 'Add celery', 'Wrap in lettuce'],
    prepTime: 10,
    cookTime: 0,
  },
  {
    id: 'ln-4',
    name: 'Chicken & Brown Rice',
    category: 'lunch',
    protein: 48,
    carbs: 50,
    fats: 12,
    calories: 500,
    ingredients: ['8 oz chicken breast', 'Brown rice', 'Broccoli', 'Soy sauce', 'Garlic'],
    instructions: ['Cook chicken and rice', 'Steam broccoli', 'Season and serve'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'ln-5',
    name: 'Protein-Packed Wrap',
    category: 'lunch',
    protein: 40,
    carbs: 35,
    fats: 15,
    calories: 420,
    ingredients: ['Whole wheat tortilla', 'Chicken', 'Hummus', 'Vegetables', 'Feta cheese'],
    instructions: ['Warm tortilla', 'Spread hummus', 'Add fillings', 'Roll tightly'],
    prepTime: 5,
    cookTime: 10,
  },
  {
    id: 'ln-6',
    name: 'Salmon & Sweet Potato',
    category: 'lunch',
    protein: 44,
    carbs: 42,
    fats: 18,
    calories: 480,
    ingredients: ['6 oz salmon', 'Sweet potato', 'Asparagus', 'Lemon', 'Herbs'],
    instructions: ['Bake salmon and sweet potato', 'Roast asparagus', 'Season and serve'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'ln-7',
    name: 'Lean Beef & Vegetables',
    category: 'lunch',
    protein: 46,
    carbs: 20,
    fats: 20,
    calories: 440,
    ingredients: ['6 oz lean beef', 'Mixed vegetables', 'Olive oil', 'Garlic', 'Herbs'],
    instructions: ['Stir-fry beef', 'Add vegetables', 'Season and serve'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'ln-8',
    name: 'Chicken Caesar Salad',
    category: 'lunch',
    protein: 42,
    carbs: 18,
    fats: 22,
    calories: 420,
    ingredients: ['Chicken breast', 'Romaine lettuce', 'Parmesan', 'Caesar dressing', 'Croutons'],
    instructions: ['Grill chicken', 'Toss salad', 'Add dressing and toppings'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'ln-9',
    name: 'Turkey Burger',
    category: 'lunch',
    protein: 44,
    carbs: 32,
    fats: 16,
    calories: 440,
    ingredients: ['Turkey patty', 'Whole grain bun', 'Lettuce', 'Tomato', 'Onion'],
    instructions: ['Cook turkey patty', 'Toast bun', 'Assemble burger'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'ln-10',
    name: 'Shrimp & Quinoa Salad',
    category: 'lunch',
    protein: 40,
    carbs: 38,
    fats: 14,
    calories: 420,
    ingredients: ['Shrimp', 'Quinoa', 'Mixed greens', 'Avocado', 'Lime vinaigrette'],
    instructions: ['Cook shrimp and quinoa', 'Toss with greens', 'Add avocado and dressing'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'ln-11',
    name: 'Chicken Stir-Fry',
    category: 'lunch',
    protein: 46,
    carbs: 35,
    fats: 12,
    calories: 440,
    ingredients: ['Chicken breast', 'Broccoli', 'Bell peppers', 'Soy sauce', 'Ginger'],
    instructions: ['Stir-fry chicken', 'Add vegetables', 'Season with sauce'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'ln-12',
    name: 'Greek Chicken Bowl',
    category: 'lunch',
    protein: 44,
    carbs: 40,
    fats: 16,
    calories: 460,
    ingredients: ['Chicken', 'Brown rice', 'Cucumber', 'Tomatoes', 'Feta', 'Tzatziki'],
    instructions: ['Cook chicken and rice', 'Chop vegetables', 'Assemble bowl'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'ln-13',
    name: 'Tuna Poke Bowl',
    category: 'lunch',
    protein: 42,
    carbs: 45,
    fats: 12,
    calories: 460,
    ingredients: ['Fresh tuna', 'Sushi rice', 'Avocado', 'Cucumber', 'Soy sauce'],
    instructions: ['Cube tuna', 'Prepare rice', 'Assemble bowl with toppings'],
    prepTime: 15,
    cookTime: 20,
  },
  {
    id: 'ln-14',
    name: 'Chicken & Vegetable Soup',
    category: 'lunch',
    protein: 38,
    carbs: 25,
    fats: 10,
    calories: 340,
    ingredients: ['Chicken breast', 'Vegetables', 'Chicken broth', 'Herbs', 'Noodles'],
    instructions: ['Cook chicken', 'Add vegetables and broth', 'Simmer 20 minutes'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'ln-15',
    name: 'Beef & Broccoli',
    category: 'lunch',
    protein: 48,
    carbs: 30,
    fats: 18,
    calories: 460,
    ingredients: ['Lean beef', 'Broccoli', 'Brown rice', 'Soy sauce', 'Garlic'],
    instructions: ['Stir-fry beef', 'Add broccoli', 'Serve over rice'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'ln-16',
    name: 'Chicken Fajita Bowl',
    category: 'lunch',
    protein: 46,
    carbs: 38,
    fats: 14,
    calories: 460,
    ingredients: ['Chicken', 'Bell peppers', 'Onions', 'Brown rice', 'Salsa', 'Sour cream'],
    instructions: ['Cook chicken and vegetables', 'Prepare rice', 'Assemble bowl'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'ln-17',
    name: 'Salmon Salad Sandwich',
    category: 'lunch',
    protein: 40,
    carbs: 32,
    fats: 18,
    calories: 440,
    ingredients: ['Canned salmon', 'Whole grain bread', 'Greek yogurt', 'Lettuce', 'Tomato'],
    instructions: ['Mix salmon with yogurt', 'Toast bread', 'Assemble sandwich'],
    prepTime: 5,
    cookTime: 5,
  },
  {
    id: 'ln-18',
    name: 'Chicken & Black Bean Bowl',
    category: 'lunch',
    protein: 44,
    carbs: 42,
    fats: 12,
    calories: 460,
    ingredients: ['Chicken', 'Black beans', 'Corn', 'Brown rice', 'Avocado', 'Cilantro'],
    instructions: ['Cook chicken and rice', 'Heat beans and corn', 'Assemble bowl'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'ln-19',
    name: 'Turkey & Vegetable Skewers',
    category: 'lunch',
    protein: 42,
    carbs: 20,
    fats: 14,
    calories: 380,
    ingredients: ['Turkey chunks', 'Bell peppers', 'Zucchini', 'Onions', 'Marinade'],
    instructions: ['Marinate turkey', 'Thread on skewers', 'Grill 15 minutes'],
    prepTime: 15,
    cookTime: 15,
  },
  {
    id: 'ln-20',
    name: 'Chicken & Lentil Salad',
    category: 'lunch',
    protein: 46,
    carbs: 40,
    fats: 14,
    calories: 480,
    ingredients: ['Chicken breast', 'Cooked lentils', 'Mixed greens', 'Feta', 'Vinaigrette'],
    instructions: ['Cook chicken and lentils', 'Toss with greens', 'Add cheese and dressing'],
    prepTime: 10,
    cookTime: 20,
  },
  
  // Dinner Recipes (20)
  {
    id: 'dn-1',
    name: 'Grilled Salmon & Vegetables',
    category: 'dinner',
    protein: 46,
    carbs: 15,
    fats: 22,
    calories: 440,
    ingredients: ['8 oz salmon', 'Asparagus', 'Broccoli', 'Lemon', 'Herbs'],
    instructions: ['Grill salmon', 'Roast vegetables', 'Season and serve'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'dn-2',
    name: 'Chicken & Sweet Potato',
    category: 'dinner',
    protein: 48,
    carbs: 45,
    fats: 14,
    calories: 500,
    ingredients: ['8 oz chicken breast', 'Sweet potato', 'Green beans', 'Olive oil'],
    instructions: ['Bake chicken and sweet potato', 'Steam green beans', 'Serve together'],
    prepTime: 10,
    cookTime: 30,
  },
  {
    id: 'dn-3',
    name: 'Lean Beef Steak & Salad',
    category: 'dinner',
    protein: 50,
    carbs: 12,
    fats: 24,
    calories: 480,
    ingredients: ['8 oz sirloin', 'Mixed greens', 'Cherry tomatoes', 'Balsamic vinaigrette'],
    instructions: ['Grill steak', 'Prepare salad', 'Serve together'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'dn-4',
    name: 'Turkey Meatballs & Zoodles',
    category: 'dinner',
    protein: 44,
    carbs: 18,
    fats: 16,
    calories: 400,
    ingredients: ['Turkey meatballs', 'Zucchini noodles', 'Marinara sauce', 'Parmesan'],
    instructions: ['Cook meatballs', 'Sauté zoodles', 'Combine with sauce'],
    prepTime: 15,
    cookTime: 20,
  },
  {
    id: 'dn-5',
    name: 'Chicken & Quinoa Casserole',
    category: 'dinner',
    protein: 46,
    carbs: 42,
    fats: 14,
    calories: 480,
    ingredients: ['Chicken breast', 'Quinoa', 'Vegetables', 'Cheese', 'Herbs'],
    instructions: ['Cook chicken and quinoa', 'Mix with vegetables', 'Bake 25 minutes'],
    prepTime: 15,
    cookTime: 30,
  },
  {
    id: 'dn-6',
    name: 'Baked Cod & Vegetables',
    category: 'dinner',
    protein: 42,
    carbs: 20,
    fats: 12,
    calories: 360,
    ingredients: ['6 oz cod', 'Carrots', 'Brussels sprouts', 'Lemon', 'Herbs'],
    instructions: ['Bake cod and vegetables', 'Season with herbs', 'Serve hot'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'dn-7',
    name: 'Chicken Thighs & Rice',
    category: 'dinner',
    protein: 44,
    carbs: 48,
    fats: 18,
    calories: 520,
    ingredients: ['Chicken thighs', 'Brown rice', 'Broccoli', 'Soy sauce'],
    instructions: ['Cook chicken and rice', 'Steam broccoli', 'Season and serve'],
    prepTime: 10,
    cookTime: 30,
  },
  {
    id: 'dn-8',
    name: 'Pork Tenderloin & Vegetables',
    category: 'dinner',
    protein: 48,
    carbs: 15,
    fats: 16,
    calories: 400,
    ingredients: ['6 oz pork tenderloin', 'Mixed vegetables', 'Olive oil', 'Herbs'],
    instructions: ['Roast pork', 'Roast vegetables', 'Serve together'],
    prepTime: 10,
    cookTime: 30,
  },
  {
    id: 'dn-9',
    name: 'Chicken & Vegetable Skewers',
    category: 'dinner',
    protein: 46,
    carbs: 18,
    fats: 14,
    calories: 400,
    ingredients: ['Chicken chunks', 'Bell peppers', 'Onions', 'Zucchini', 'Marinade'],
    instructions: ['Marinate chicken', 'Thread on skewers', 'Grill 20 minutes'],
    prepTime: 15,
    cookTime: 20,
  },
  {
    id: 'dn-10',
    name: 'Salmon & Asparagus',
    category: 'dinner',
    protein: 44,
    carbs: 8,
    fats: 20,
    calories: 380,
    ingredients: ['6 oz salmon', 'Asparagus', 'Lemon', 'Butter', 'Herbs'],
    instructions: ['Bake salmon', 'Roast asparagus', 'Season and serve'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'dn-11',
    name: 'Chicken & Broccoli Stir-Fry',
    category: 'dinner',
    protein: 48,
    carbs: 25,
    fats: 12,
    calories: 420,
    ingredients: ['Chicken breast', 'Broccoli', 'Carrots', 'Soy sauce', 'Ginger'],
    instructions: ['Stir-fry chicken', 'Add vegetables', 'Season with sauce'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'dn-12',
    name: 'Beef & Vegetable Stew',
    category: 'dinner',
    protein: 46,
    carbs: 30,
    fats: 16,
    calories: 460,
    ingredients: ['Lean beef', 'Vegetables', 'Beef broth', 'Herbs', 'Potatoes'],
    instructions: ['Brown beef', 'Add vegetables and broth', 'Simmer 45 minutes'],
    prepTime: 15,
    cookTime: 50,
  },
  {
    id: 'dn-13',
    name: 'Grilled Chicken & Corn',
    category: 'dinner',
    protein: 48,
    carbs: 38,
    fats: 14,
    calories: 480,
    ingredients: ['8 oz chicken breast', 'Corn on cob', 'Green beans', 'Butter'],
    instructions: ['Grill chicken and corn', 'Steam green beans', 'Serve together'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'dn-14',
    name: 'Tuna Steak & Vegetables',
    category: 'dinner',
    protein: 50,
    carbs: 12,
    fats: 18,
    calories: 420,
    ingredients: ['6 oz tuna steak', 'Mixed vegetables', 'Olive oil', 'Lemon'],
    instructions: ['Sear tuna', 'Roast vegetables', 'Serve together'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'dn-15',
    name: 'Chicken & Cauliflower Rice',
    category: 'dinner',
    protein: 46,
    carbs: 15,
    fats: 14,
    calories: 380,
    ingredients: ['Chicken breast', 'Cauliflower rice', 'Vegetables', 'Soy sauce'],
    instructions: ['Cook chicken', 'Sauté cauliflower rice', 'Combine and season'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'dn-16',
    name: 'Turkey & Sweet Potato Hash',
    category: 'dinner',
    protein: 44,
    carbs: 42,
    fats: 16,
    calories: 480,
    ingredients: ['Ground turkey', 'Sweet potatoes', 'Onions', 'Peppers', 'Eggs'],
    instructions: ['Cook turkey', 'Add vegetables', 'Top with fried eggs'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'dn-17',
    name: 'Chicken & Lentil Curry',
    category: 'dinner',
    protein: 46,
    carbs: 40,
    fats: 14,
    calories: 480,
    ingredients: ['Chicken', 'Lentils', 'Curry spices', 'Coconut milk', 'Vegetables'],
    instructions: ['Cook chicken', 'Add lentils and spices', 'Simmer with coconut milk'],
    prepTime: 15,
    cookTime: 30,
  },
  {
    id: 'dn-18',
    name: 'Baked Chicken & Vegetables',
    category: 'dinner',
    protein: 48,
    carbs: 20,
    fats: 16,
    calories: 420,
    ingredients: ['Chicken breast', 'Mixed vegetables', 'Olive oil', 'Herbs'],
    instructions: ['Arrange on baking sheet', 'Drizzle with oil', 'Bake 30 minutes'],
    prepTime: 10,
    cookTime: 30,
  },
  {
    id: 'dn-19',
    name: 'Salmon & Quinoa Bowl',
    category: 'dinner',
    protein: 44,
    carbs: 38,
    fats: 18,
    calories: 480,
    ingredients: ['6 oz salmon', 'Quinoa', 'Vegetables', 'Avocado', 'Lemon'],
    instructions: ['Cook salmon and quinoa', 'Roast vegetables', 'Assemble bowl'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'dn-20',
    name: 'Chicken & Vegetable Kebabs',
    category: 'dinner',
    protein: 46,
    carbs: 18,
    fats: 14,
    calories: 400,
    ingredients: ['Chicken chunks', 'Vegetables', 'Marinade', 'Skewers'],
    instructions: ['Marinate chicken', 'Thread on skewers', 'Grill 20 minutes'],
    prepTime: 15,
    cookTime: 20,
  },
  
  // Dessert Recipes (20)
  {
    id: 'ds-1',
    name: 'Protein Chocolate Pudding',
    category: 'dessert',
    protein: 28,
    carbs: 25,
    fats: 8,
    calories: 280,
    ingredients: ['Chocolate protein powder', 'Greek yogurt', 'Cocoa powder', 'Stevia'],
    instructions: ['Mix protein with yogurt', 'Add cocoa', 'Sweeten to taste', 'Chill'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'ds-2',
    name: 'Protein Brownies',
    category: 'dessert',
    protein: 24,
    carbs: 22,
    fats: 10,
    calories: 260,
    ingredients: ['Protein powder', 'Almond flour', 'Eggs', 'Cocoa', 'Stevia'],
    instructions: ['Mix ingredients', 'Bake at 350°F for 20 min', 'Cool and cut'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'ds-3',
    name: 'Greek Yogurt Cheesecake',
    category: 'dessert',
    protein: 26,
    carbs: 20,
    fats: 12,
    calories: 280,
    ingredients: ['Greek yogurt', 'Protein powder', 'Gelatin', 'Berries', 'Honey'],
    instructions: ['Mix yogurt with protein', 'Set with gelatin', 'Top with berries'],
    prepTime: 15,
    cookTime: 0,
  },
  {
    id: 'ds-4',
    name: 'Protein Ice Cream',
    category: 'dessert',
    protein: 22,
    carbs: 18,
    fats: 6,
    calories: 220,
    ingredients: ['Protein powder', 'Frozen bananas', 'Almond milk', 'Vanilla'],
    instructions: ['Blend all ingredients', 'Freeze 2 hours', 'Serve'],
    prepTime: 10,
    cookTime: 0,
  },
  {
    id: 'ds-5',
    name: 'Protein Cookies',
    category: 'dessert',
    protein: 20,
    carbs: 20,
    fats: 8,
    calories: 240,
    ingredients: ['Protein powder', 'Oats', 'Almond butter', 'Eggs', 'Chocolate chips'],
    instructions: ['Mix ingredients', 'Form cookies', 'Bake 12 minutes'],
    prepTime: 10,
    cookTime: 12,
  },
  {
    id: 'ds-6',
    name: 'Chocolate Protein Mousse',
    category: 'dessert',
    protein: 26,
    carbs: 15,
    fats: 10,
    calories: 250,
    ingredients: ['Chocolate protein', 'Greek yogurt', 'Cocoa', 'Stevia'],
    instructions: ['Whip yogurt', 'Fold in protein', 'Chill and serve'],
    prepTime: 10,
    cookTime: 0,
  },
  {
    id: 'ds-7',
    name: 'Protein Bars',
    category: 'dessert',
    protein: 24,
    carbs: 22,
    fats: 10,
    calories: 280,
    ingredients: ['Protein powder', 'Nuts', 'Dates', 'Coconut oil', 'Vanilla'],
    instructions: ['Process dates and nuts', 'Mix with protein', 'Press and chill'],
    prepTime: 15,
    cookTime: 0,
  },
  {
    id: 'ds-8',
    name: 'Protein Pancake Stack',
    category: 'dessert',
    protein: 28,
    carbs: 25,
    fats: 8,
    calories: 280,
    ingredients: ['Protein pancakes', 'Greek yogurt', 'Berries', 'Honey'],
    instructions: ['Stack pancakes', 'Layer with yogurt', 'Top with berries'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'ds-9',
    name: 'Chocolate Protein Smoothie',
    category: 'dessert',
    protein: 30,
    carbs: 28,
    fats: 6,
    calories: 280,
    ingredients: ['Chocolate protein', 'Banana', 'Almond milk', 'Ice', 'PB2'],
    instructions: ['Blend all ingredients', 'Serve cold'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'ds-10',
    name: 'Protein Cheesecake Bites',
    category: 'dessert',
    protein: 24,
    carbs: 18,
    fats: 10,
    calories: 260,
    ingredients: ['Greek yogurt', 'Protein powder', 'Gelatin', 'Vanilla'],
    instructions: ['Mix ingredients', 'Pour into molds', 'Chill 4 hours'],
    prepTime: 10,
    cookTime: 0,
  },
  {
    id: 'ds-11',
    name: 'Protein Fudge',
    category: 'dessert',
    protein: 22,
    carbs: 20,
    fats: 12,
    calories: 280,
    ingredients: ['Protein powder', 'Almond butter', 'Cocoa', 'Coconut oil'],
    instructions: ['Melt ingredients', 'Mix together', 'Chill and cut'],
    prepTime: 10,
    cookTime: 0,
  },
  {
    id: 'ds-12',
    name: 'Protein Tiramisu',
    category: 'dessert',
    protein: 26,
    carbs: 22,
    fats: 10,
    calories: 280,
    ingredients: ['Protein powder', 'Greek yogurt', 'Coffee', 'Cocoa'],
    instructions: ['Layer yogurt and protein', 'Drizzle coffee', 'Dust with cocoa'],
    prepTime: 15,
    cookTime: 0,
  },
  {
    id: 'ds-13',
    name: 'Protein Donuts',
    category: 'dessert',
    protein: 20,
    carbs: 20,
    fats: 8,
    calories: 240,
    ingredients: ['Protein powder', 'Almond flour', 'Eggs', 'Baking powder'],
    instructions: ['Mix batter', 'Bake in donut pan', 'Glaze and serve'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'ds-14',
    name: 'Protein Parfait',
    category: 'dessert',
    protein: 28,
    carbs: 25,
    fats: 8,
    calories: 280,
    ingredients: ['Greek yogurt', 'Protein powder', 'Granola', 'Berries'],
    instructions: ['Layer yogurt and protein', 'Add granola', 'Top with berries'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'ds-15',
    name: 'Chocolate Protein Cake',
    category: 'dessert',
    protein: 24,
    carbs: 22,
    fats: 10,
    calories: 280,
    ingredients: ['Protein powder', 'Almond flour', 'Eggs', 'Cocoa', 'Stevia'],
    instructions: ['Mix ingredients', 'Bake 25 minutes', 'Cool and serve'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'ds-16',
    name: 'Protein Popsicles',
    category: 'dessert',
    protein: 20,
    carbs: 18,
    fats: 4,
    calories: 200,
    ingredients: ['Protein powder', 'Greek yogurt', 'Fruit', 'Honey'],
    instructions: ['Blend ingredients', 'Pour into molds', 'Freeze 4 hours'],
    prepTime: 10,
    cookTime: 0,
  },
  {
    id: 'ds-17',
    name: 'Protein Truffles',
    category: 'dessert',
    protein: 22,
    carbs: 15,
    fats: 12,
    calories: 260,
    ingredients: ['Protein powder', 'Almond butter', 'Cocoa', 'Coconut'],
    instructions: ['Mix ingredients', 'Form balls', 'Roll in coconut'],
    prepTime: 15,
    cookTime: 0,
  },
  {
    id: 'ds-18',
    name: 'Protein Cinnamon Rolls',
    category: 'dessert',
    protein: 24,
    carbs: 25,
    fats: 8,
    calories: 280,
    ingredients: ['Protein powder', 'Almond flour', 'Cinnamon', 'Greek yogurt'],
    instructions: ['Make dough', 'Roll and fill', 'Bake 20 minutes'],
    prepTime: 20,
    cookTime: 20,
  },
  {
    id: 'ds-19',
    name: 'Protein Chocolate Chip Cookies',
    category: 'dessert',
    protein: 22,
    carbs: 22,
    fats: 10,
    calories: 280,
    ingredients: ['Protein powder', 'Almond flour', 'Eggs', 'Chocolate chips'],
    instructions: ['Mix ingredients', 'Form cookies', 'Bake 12 minutes'],
    prepTime: 10,
    cookTime: 12,
  },
  {
    id: 'ds-20',
    name: 'Protein Banana Bread',
    category: 'dessert',
    protein: 26,
    carbs: 28,
    fats: 8,
    calories: 300,
    ingredients: ['Protein powder', 'Bananas', 'Oats', 'Eggs', 'Nuts'],
    instructions: ['Mash bananas', 'Mix ingredients', 'Bake 45 minutes'],
    prepTime: 10,
    cookTime: 45,
  },
  
  // Pre-Workout Recipes (20)
  {
    id: 'pre-1',
    name: 'Banana & Protein Smoothie',
    category: 'pre-workout',
    protein: 25,
    carbs: 35,
    fats: 5,
    calories: 280,
    ingredients: ['Banana', 'Protein powder', 'Oats', 'Honey', 'Almond milk'],
    instructions: ['Blend all ingredients', 'Drink 30 min before workout'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'pre-2',
    name: 'Oatmeal & Berries',
    category: 'pre-workout',
    protein: 12,
    carbs: 45,
    fats: 6,
    calories: 280,
    ingredients: ['Oats', 'Berries', 'Honey', 'Almond milk', 'Chia seeds'],
    instructions: ['Cook oats', 'Top with berries', 'Drizzle honey'],
    prepTime: 5,
    cookTime: 10,
  },
  {
    id: 'pre-3',
    name: 'Rice Cake & Peanut Butter',
    category: 'pre-workout',
    protein: 10,
    carbs: 30,
    fats: 8,
    calories: 220,
    ingredients: ['Rice cakes', 'Peanut butter', 'Banana slices', 'Honey'],
    instructions: ['Spread PB on rice cakes', 'Top with banana', 'Drizzle honey'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'pre-4',
    name: 'Energy Balls',
    category: 'pre-workout',
    protein: 8,
    carbs: 28,
    fats: 10,
    calories: 240,
    ingredients: ['Dates', 'Oats', 'Almonds', 'Honey', 'Coconut'],
    instructions: ['Process ingredients', 'Form balls', 'Chill'],
    prepTime: 10,
    cookTime: 0,
  },
  {
    id: 'pre-5',
    name: 'Greek Yogurt & Fruit',
    category: 'pre-workout',
    protein: 20,
    carbs: 30,
    fats: 4,
    calories: 240,
    ingredients: ['Greek yogurt', 'Banana', 'Berries', 'Honey', 'Granola'],
    instructions: ['Mix yogurt with fruit', 'Top with granola', 'Drizzle honey'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'pre-6',
    name: 'Sweet Potato & Almond Butter',
    category: 'pre-workout',
    protein: 8,
    carbs: 40,
    fats: 12,
    calories: 300,
    ingredients: ['Sweet potato', 'Almond butter', 'Cinnamon', 'Honey'],
    instructions: ['Bake sweet potato', 'Top with almond butter', 'Season'],
    prepTime: 5,
    cookTime: 45,
  },
  {
    id: 'pre-7',
    name: 'Banana Bread Slice',
    category: 'pre-workout',
    protein: 6,
    carbs: 35,
    fats: 8,
    calories: 240,
    ingredients: ['Banana bread', 'Almond butter', 'Honey'],
    instructions: ['Toast bread', 'Spread almond butter', 'Drizzle honey'],
    prepTime: 5,
    cookTime: 5,
  },
  {
    id: 'pre-8',
    name: 'Apple & Peanut Butter',
    category: 'pre-workout',
    protein: 8,
    carbs: 25,
    fats: 10,
    calories: 220,
    ingredients: ['Apple', 'Peanut butter', 'Cinnamon'],
    instructions: ['Slice apple', 'Dip in peanut butter', 'Sprinkle cinnamon'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'pre-9',
    name: 'Pre-Workout Smoothie Bowl',
    category: 'pre-workout',
    protein: 22,
    carbs: 38,
    fats: 6,
    calories: 300,
    ingredients: ['Banana', 'Oats', 'Protein powder', 'Berries', 'Honey'],
    instructions: ['Blend ingredients', 'Pour into bowl', 'Top with berries'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'pre-10',
    name: 'Whole Grain Toast & Jam',
    category: 'pre-workout',
    protein: 8,
    carbs: 32,
    fats: 4,
    calories: 200,
    ingredients: ['Whole grain bread', 'Jam', 'Banana slices'],
    instructions: ['Toast bread', 'Spread jam', 'Top with banana'],
    prepTime: 5,
    cookTime: 5,
  },
  {
    id: 'pre-11',
    name: 'Overnight Oats',
    category: 'pre-workout',
    protein: 15,
    carbs: 42,
    fats: 8,
    calories: 300,
    ingredients: ['Oats', 'Almond milk', 'Banana', 'Honey', 'Chia seeds'],
    instructions: ['Mix ingredients', 'Refrigerate overnight', 'Eat cold'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'pre-12',
    name: 'Fruit & Nut Mix',
    category: 'pre-workout',
    protein: 10,
    carbs: 28,
    fats: 12,
    calories: 260,
    ingredients: ['Dried fruits', 'Almonds', 'Cashews', 'Raisins'],
    instructions: ['Mix all ingredients', 'Portion into servings'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'pre-13',
    name: 'Banana & Honey Toast',
    category: 'pre-workout',
    protein: 8,
    carbs: 35,
    fats: 6,
    calories: 220,
    ingredients: ['Whole grain bread', 'Banana', 'Honey', 'Cinnamon'],
    instructions: ['Toast bread', 'Mash banana on top', 'Drizzle honey'],
    prepTime: 5,
    cookTime: 5,
  },
  {
    id: 'pre-14',
    name: 'Cereal & Milk',
    category: 'pre-workout',
    protein: 12,
    carbs: 38,
    fats: 6,
    calories: 260,
    ingredients: ['Whole grain cereal', 'Milk', 'Banana', 'Berries'],
    instructions: ['Pour cereal', 'Add milk', 'Top with fruit'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'pre-15',
    name: 'Energy Drink & Banana',
    category: 'pre-workout',
    protein: 2,
    carbs: 30,
    fats: 0,
    calories: 130,
    ingredients: ['Banana', 'Energy drink', 'Optional: protein powder'],
    instructions: ['Eat banana', 'Drink energy drink', 'Wait 15-30 min'],
    prepTime: 2,
    cookTime: 0,
  },
  {
    id: 'pre-16',
    name: 'Dates & Almonds',
    category: 'pre-workout',
    protein: 8,
    carbs: 32,
    fats: 10,
    calories: 260,
    ingredients: ['Dates', 'Almonds', 'Optional: dark chocolate'],
    instructions: ['Eat dates with almonds', 'Consume 30 min before'],
    prepTime: 2,
    cookTime: 0,
  },
  {
    id: 'pre-17',
    name: 'Muffin & Protein Shake',
    category: 'pre-workout',
    protein: 25,
    carbs: 35,
    fats: 8,
    calories: 300,
    ingredients: ['Whole grain muffin', 'Protein powder', 'Almond milk'],
    instructions: ['Mix protein shake', 'Eat with muffin'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'pre-18',
    name: 'Pancakes & Syrup',
    category: 'pre-workout',
    protein: 12,
    carbs: 40,
    fats: 6,
    calories: 260,
    ingredients: ['Whole grain pancakes', 'Maple syrup', 'Berries'],
    instructions: ['Cook pancakes', 'Drizzle syrup', 'Top with berries'],
    prepTime: 10,
    cookTime: 10,
  },
  {
    id: 'pre-19',
    name: 'Granola Bar',
    category: 'pre-workout',
    protein: 6,
    carbs: 28,
    fats: 8,
    calories: 220,
    ingredients: ['Granola bar', 'Optional: banana'],
    instructions: ['Eat granola bar', 'Pair with banana if needed'],
    prepTime: 2,
    cookTime: 0,
  },
  {
    id: 'pre-20',
    name: 'Fruit Smoothie',
    category: 'pre-workout',
    protein: 4,
    carbs: 38,
    fats: 2,
    calories: 180,
    ingredients: ['Banana', 'Berries', 'Orange juice', 'Honey'],
    instructions: ['Blend all ingredients', 'Drink 30 min before'],
    prepTime: 5,
    cookTime: 0,
  },
  
  // Post-Workout Recipes (20)
  {
    id: 'post-1',
    name: 'Chocolate Protein Shake',
    category: 'post-workout',
    protein: 40,
    carbs: 35,
    fats: 8,
    calories: 360,
    ingredients: ['Chocolate protein powder', 'Banana', 'Almond milk', 'Oats'],
    instructions: ['Blend all ingredients', 'Drink immediately after workout'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'post-2',
    name: 'Chicken & Rice Bowl',
    category: 'post-workout',
    protein: 48,
    carbs: 50,
    fats: 12,
    calories: 500,
    ingredients: ['8 oz chicken breast', 'Brown rice', 'Vegetables', 'Sauce'],
    instructions: ['Cook chicken and rice', 'Steam vegetables', 'Assemble bowl'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'post-3',
    name: 'Protein Pancakes',
    category: 'post-workout',
    protein: 38,
    carbs: 30,
    fats: 10,
    calories: 360,
    ingredients: ['Protein powder', 'Eggs', 'Banana', 'Oat flour'],
    instructions: ['Mix ingredients', 'Cook pancakes', 'Top with fruit'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'post-4',
    name: 'Salmon & Sweet Potato',
    category: 'post-workout',
    protein: 44,
    carbs: 45,
    fats: 18,
    calories: 500,
    ingredients: ['6 oz salmon', 'Sweet potato', 'Broccoli', 'Lemon'],
    instructions: ['Bake salmon and sweet potato', 'Steam broccoli', 'Serve'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'post-5',
    name: 'Greek Yogurt & Granola',
    category: 'post-workout',
    protein: 35,
    carbs: 40,
    fats: 10,
    calories: 400,
    ingredients: ['Greek yogurt', 'Protein powder', 'Granola', 'Berries', 'Honey'],
    instructions: ['Mix yogurt with protein', 'Top with granola and berries'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'post-6',
    name: 'Turkey & Quinoa',
    category: 'post-workout',
    protein: 46,
    carbs: 42,
    fats: 14,
    calories: 480,
    ingredients: ['6 oz turkey', 'Quinoa', 'Vegetables', 'Avocado'],
    instructions: ['Cook turkey and quinoa', 'Roast vegetables', 'Assemble'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'post-7',
    name: 'Protein Oatmeal',
    category: 'post-workout',
    protein: 32,
    carbs: 45,
    fats: 12,
    calories: 420,
    ingredients: ['Oats', 'Protein powder', 'Banana', 'Nuts', 'Honey'],
    instructions: ['Cook oats', 'Stir in protein', 'Top with banana and nuts'],
    prepTime: 5,
    cookTime: 10,
  },
  {
    id: 'post-8',
    name: 'Eggs & Toast',
    category: 'post-workout',
    protein: 28,
    carbs: 35,
    fats: 14,
    calories: 380,
    ingredients: ['4 eggs', 'Whole grain toast', 'Avocado', 'Tomato'],
    instructions: ['Scramble eggs', 'Toast bread', 'Serve with avocado'],
    prepTime: 5,
    cookTime: 10,
  },
  {
    id: 'post-9',
    name: 'Beef & Potatoes',
    category: 'post-workout',
    protein: 48,
    carbs: 42,
    fats: 18,
    calories: 520,
    ingredients: ['6 oz lean beef', 'Potatoes', 'Vegetables', 'Herbs'],
    instructions: ['Cook beef', 'Roast potatoes', 'Steam vegetables'],
    prepTime: 10,
    cookTime: 30,
  },
  {
    id: 'post-10',
    name: 'Tuna & Pasta',
    category: 'post-workout',
    protein: 42,
    carbs: 48,
    fats: 12,
    calories: 480,
    ingredients: ['Canned tuna', 'Whole grain pasta', 'Olive oil', 'Vegetables'],
    instructions: ['Cook pasta', 'Mix with tuna', 'Add vegetables and oil'],
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 'post-11',
    name: 'Protein Smoothie Bowl',
    category: 'post-workout',
    protein: 38,
    carbs: 38,
    fats: 10,
    calories: 400,
    ingredients: ['Protein powder', 'Frozen fruits', 'Banana', 'Granola', 'Nuts'],
    instructions: ['Blend fruits with protein', 'Pour into bowl', 'Top with granola'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'post-12',
    name: 'Chicken & Pasta',
    category: 'post-workout',
    protein: 46,
    carbs: 45,
    fats: 14,
    calories: 500,
    ingredients: ['Chicken breast', 'Whole grain pasta', 'Tomato sauce', 'Cheese'],
    instructions: ['Cook chicken and pasta', 'Mix with sauce', 'Top with cheese'],
    prepTime: 10,
    cookTime: 20,
  },
  {
    id: 'post-13',
    name: 'Protein Waffles',
    category: 'post-workout',
    protein: 36,
    carbs: 32,
    fats: 10,
    calories: 360,
    ingredients: ['Protein powder', 'Eggs', 'Oat flour', 'Banana'],
    instructions: ['Mix batter', 'Cook in waffle iron', 'Top with banana'],
    prepTime: 10,
    cookTime: 10,
  },
  {
    id: 'post-14',
    name: 'Salmon & Rice',
    category: 'post-workout',
    protein: 44,
    carbs: 48,
    fats: 16,
    calories: 500,
    ingredients: ['6 oz salmon', 'Brown rice', 'Vegetables', 'Soy sauce'],
    instructions: ['Cook salmon and rice', 'Steam vegetables', 'Season'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'post-15',
    name: 'Protein Bar & Banana',
    category: 'post-workout',
    protein: 30,
    carbs: 35,
    fats: 10,
    calories: 360,
    ingredients: ['Protein bar', 'Banana', 'Optional: milk'],
    instructions: ['Eat protein bar', 'Pair with banana', 'Drink milk if desired'],
    prepTime: 2,
    cookTime: 0,
  },
  {
    id: 'post-16',
    name: 'Chicken & Sweet Potato',
    category: 'post-workout',
    protein: 48,
    carbs: 45,
    fats: 14,
    calories: 500,
    ingredients: ['8 oz chicken', 'Sweet potato', 'Green beans', 'Herbs'],
    instructions: ['Bake chicken and sweet potato', 'Steam green beans'],
    prepTime: 10,
    cookTime: 30,
  },
  {
    id: 'post-17',
    name: 'Protein French Toast',
    category: 'post-workout',
    protein: 32,
    carbs: 38,
    fats: 12,
    calories: 400,
    ingredients: ['Whole grain bread', 'Eggs', 'Protein powder', 'Berries'],
    instructions: ['Dip bread in egg mixture', 'Cook on griddle', 'Top with berries'],
    prepTime: 10,
    cookTime: 10,
  },
  {
    id: 'post-18',
    name: 'Turkey & Rice',
    category: 'post-workout',
    protein: 44,
    carbs: 48,
    fats: 12,
    calories: 480,
    ingredients: ['6 oz turkey', 'Brown rice', 'Vegetables', 'Sauce'],
    instructions: ['Cook turkey and rice', 'Steam vegetables', 'Combine'],
    prepTime: 10,
    cookTime: 25,
  },
  {
    id: 'post-19',
    name: 'Protein Overnight Oats',
    category: 'post-workout',
    protein: 34,
    carbs: 45,
    fats: 12,
    calories: 440,
    ingredients: ['Oats', 'Protein powder', 'Greek yogurt', 'Banana', 'Nuts'],
    instructions: ['Mix ingredients', 'Refrigerate', 'Top with banana and nuts'],
    prepTime: 5,
    cookTime: 0,
  },
  {
    id: 'post-20',
    name: 'Steak & Potatoes',
    category: 'post-workout',
    protein: 50,
    carbs: 40,
    fats: 20,
    calories: 540,
    ingredients: ['8 oz steak', 'Potatoes', 'Vegetables', 'Butter'],
    instructions: ['Cook steak', 'Roast potatoes', 'Steam vegetables'],
    prepTime: 10,
    cookTime: 30,
  },
];

// Helper function to add images to recipes
function addImagesToRecipes(recipesArray: Recipe[]): Recipe[] {
  const categoryCounts: Record<string, number> = {};
  return recipesArray.map((recipe) => {
    if (!categoryCounts[recipe.category]) {
      categoryCounts[recipe.category] = 0;
    }
    const categoryIndex = categoryCounts[recipe.category]++;
    return {
      ...recipe,
      image: recipe.image || getFoodImageUrl(recipe.category, categoryIndex),
    };
  });
}

// Add images to all recipes
export const recipes: Recipe[] = addImagesToRecipes(recipesData);
